spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/dev_bondlinc_engine
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
bondlic:
  allowApiKeys: KKKKKKK;BBBBBBB;
